# Generated by Django 5.2.6 on 2025-10-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_make_fecha_hora_not_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha_hora'], 'verbose_name_plural': 'Bitácora'},
        ),
    ]
